INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (3, 'Centro de Convenções Ulysses Guimarães', 'Eixo Monumental - SDC (Setor de Divulgação Cultural), entre a Torre de TV e o Memorial JK', '(61) 3325-6378', NULL, 'Segunda a sexta-feira, das 9h às 12h e das 14h às 18h', 'De frente para a Esplanada dos Ministérios e a poucos minutos do núcleo das decisões políticas e econômicas, está um dos mais modernos espaços para eventos do País. Reinaugurado em 2005 após uma grande reforma, o Centro de Convenções Ulysses Guimarães tem 54 mil m² de área total. É três vezes maior do que o prédio original, construído na década de 1970.

Com capacidade para receber quase 10 mil pessoas e adaptado para portadores de necessidades especiais, o local vem sendo eleito sede de importantes encontros nacionais e internacionais. A escolha é fácil de explicar: vizinho dos três poderes, o Centro está a 15 minutos do aeroporto e ao lado do setor de hotéis. Além disso, a localização estratégica de Brasília, no centro do País, agiliza o acesso a partir de outros estados.

O edifício é dividido em alas, o que permite a realização de diferentes eventos ao mesmo tempo. Exposições e feiras podem acontecer tanto na área climatizada da ala Sul quanto no vão livre da ala Oeste. Do outro lado, quatro auditórios abrigam palestras ou apresentações de teatro e cinema. O auditório principal, que pode receber até 3 mil pessoas, fica na ala Norte. Veja as plantas do local.

O Centro de Convenções Ulysses Guimarães tem ajudado Brasília a fortalecer sua vocação para o turismo de negócios. Confira a agenda de eventos. Com um projeto arquitetônico ousado, o espaço também se tornou uma atração para qualquer visitante da capital.', 2975, 1, 4, '2009-08-26 23:34:54.482235', '2009-10-08 11:01:40.744417');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (2, 'Catetinho', 'Km 0 da BR 040, Trevo do Gama, Zona 0', '(61) 3338-8694', NULL, '', 'Simples e com estrutura toda em madeira, o Catetinho foi a primeira moradia presidencial em Brasília. A idéia da construção surgiu de uma conversa entre amigos. Enquanto o músico Dilermando Reis sugeria o nome – uma alusão ao Palácio do Catete, antiga residência do presidente no Rio de Janeiro – Oscar Niemeyer esboçou o projeto em um guardanapo.

A obra ficou pronta em apenas dez dias e, logo após a inauguração, em 10 de novembro de 1956, Juscelino Kubitschek fez o primeiro despacho oficial no Catetinho. Durante dois anos, JK morou e trabalhou na residência.

Em 1959, o Catetinho foi tombado pelo Instituto do Patrimônio Histórico e Artístico Nacional (Iphan). Hoje, o espaço não é apenas um ponto turístico. Visitar o Catetinho é como ter uma aula de história sobre a capital do Brasil e sobre JK. A casa está restaurada e é possível ver objetos pessoais do ex-presidente, como seu chapéu marrom e um pijama de seda.', 2975, 1, 4, '2009-08-26 23:33:06.512178', '2009-10-08 11:02:26.265491');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (7, 'Ermida Dom Bosco', 'SHDB – Parque Dom Bosco – QL 30', '(61) 3367-4505', NULL, '', 'A pequena igreja às margens do Lago Paranoá foi construída em homenagem ao santo São João Melchior Bosco. Reza a lenda que Dom Bosco sonhou com a criação de uma cidade onde hoje está localizada Brasília.

Projetada por Oscar Niemeyer e inaugurada em 1957, a Ermida Dom Bosco foi erguida em um pequeno morro, o que garante uma vista vislumbrante. Ao seu redor, um jardim transmite paz aos visitantes.

A Ermida faz parte de uma parque de preservação ecológica onde, também em homenagem ao santo, foi inaugurada em 2006 a Capela Dom Bosco. Igualmente bela, a obra tem um altar para a celebração de missas.

Se tiver disposição, aproveite a ida ao local para fazer trilhas e caminhadas pelo parque. O pôr-do-sol é uma atração à parte.', 2975, 1, 4, '2009-08-26 23:41:48.462913', '2009-10-08 11:07:45.413642');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (10, 'Jardim Zoológico de Brasília', 'Av. das Nações - Via L4 Sul', '(61) 3345-3280', NULL, 'De terça-feira a domingo, das 9h às 17h', 'Um dos mais conhecidos do Brasil, o Jardim Zoológico de Brasília tem ambientes semelhantes aos de selvas e florestas. Numa área de 140 hectares, lagos, ilhas, pátios e muitas árvores tentam imitar o habitat natural de mais de 250 espécies – aproximadamente 1.300 animais. Nesta variedade, estão bichos exóticos, como o faisão, e outros ameaçados de extinção, como a jaguatirica.
Mas o maior diferencial do zôo é seu caráter interativo e educacional. Durante o passeio pelo parque, é possível alimentar alguns bichinhos. Você também pode aproveitar o cenário para montar um piquenique e até fazer um churrasco nas áreas apropriadas. Só não é permitido levar bebida alcoólica.
Estudantes entre 12 e 17 anos, filhos de comerciários, podem participar de um programa de acampamento ecológico. Lá, eles aprendem na prática sobre o meio ambiente (saiba mais aqui). Outra boa opção de ensino são as visitas monitoradas, que levam a sala de aula ao zoológico.
Inaugurado em 1957, o Zoológico de Brasília é bem mais que um lugar de visitação. A estrutura do local inclui teatro de arena, auditório, biblioteca e museu e laboratório de taxidermia. Ao seu lado está o Santuário de Vida Silvestre do Riacho Fundo e o Parque das Aves. Os três espaços são administrados pela Fundação Pólo Ecológico de Brasília - FunPEB.', 2975, 1, 6, '2009-08-26 23:46:16.386106', '2009-10-08 10:56:56.868919');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (8, 'Espaço Lúcio Costa', 'Praça dos Três Poderes - subsolo', '(61) 3325-6163', NULL, 'Terça a domingo e feriados, das 9h às 18h', 'Quem chega a Brasília pela primeira vez quer entender como a capital foi concebida. Para isso, o melhor é visitar o Espaço Lúcio Costa. Com uma maquete de 170 m² do Plano Piloto e cópias de seus croquis e relatório oficial, o local é um paraíso para quem gosta de urbanismo e arquitetura.

Localizada no subterrâneo da Praça dos Três Poderes e desenhada por Oscar Niemeyer, a construção é uma homenagem ao urbanista que idealizou a cidade. Em 1957, o projeto de Lúcio Costa foi escolhido por um júri internacional entre os 26 participantes do Concurso Nacional do Plano Piloto da Nova Capital do Brasil.

Trinta anos depois, a Unesco (Organização das Nações Unidas para Educação, Ciência e Cultura) reconheceu Brasília como Patrimônio Cultural da Humanidade. A construção da capital é um divisor de águas na história da arquitetura e do urbanismo mundial.

A maquete do Plano Piloto já foi exposta em outras cidades do Brasil e no exterior. Criada em 1988, ela está no Espaço Lúcio Costa desde a inauguração do local, em 1992. Neste protótipo, há um sistema de som que transmite informações em quatro idiomas. Ao lado, fica uma maquete tátil, com legendas em Braille.', 2975, 1, 5, '2009-08-26 23:43:33.519198', '2009-10-08 10:57:26.911019');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (13, 'Palácio do Planalto', 'Praça dos Três Poderes - Zona 0', '(61) 3411-2317', NULL, 'Domingo, das 9h30 às 14h30. Não funciona em feriados. Grupos escolares precisam agendar a visita', 'A rampa por onde já passaram tantos Presidentes e Chefes de Estado pode ser escalada por cidadãos comuns. Aos domingos, dia de visita no Palácio do Planalto, você pode conhecer este e outros importantes cenários de decisões da política brasileira.

Sede do Poder Executivo desde 1960, o edifício é um dos mais conhecidos do País. O projeto, de Oscar Niemeyer, tem fachada cercada por colunas de mármore que tocam suavemente o solo, como os pilares do Palácio da Alvorada.

Do lado de dentro, quem participa do tour pode recordar cenas históricas. Muitas decisões importantes saíram de reuniões na sala da mesa oval. Nos salões das cerimônias oficiais, foram assinadas leis que podem ter mudado sua vida. Se você não se lembrar de nenhum momento marcante, os guias estarão lá para refrescar a sua memória.

Alguns cômodos ficarão apenas na sua lembrança – no terceiro andar, não é permitido fotografar. Lá estão os locais que mais despertam a curiosidade do público – como o Gabinete da Presidência da República e a Sala de Audiências. ', 2975, 1, 5, '2009-08-26 23:49:11.710032', '2009-10-08 10:58:00.242299');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (12, 'Palácio da Alvorada', 'Via Presidencial', '(61) 3411-2042', NULL, '', 'Construído para ser a residência oficial do presidente, o Palácio da Alvorada foi inaugurado em 1958. O projeto de Oscar Niemeyer ficou pronto em apenas sete meses e tornou-se um marco da arquitetura moderna.

Grandioso em tamanho e beleza, o Palácio é formado por colunas de mármore em forma de avião, que parecem tocar levemente o solo. Entre jardins, piscina olímpica, residência e anexos, somam-se 7 mil m² de área total. Nos 800 m² construídos para uso do Presidente estão a suíte do casal, com 120 m², e a biblioteca, com 150 m².

Apesar de não ser aberto para visitação, vale a pena conhecer a parte externa do edifício. Uma boa dica para quem gosta de fotografia é ir no final da tarde: a paisagem fica ainda mais bonita com o pôr-do-sol.

Além da arquitetura, outra grande atração é o famoso “Poço dos desejos”. Lembre-se de fazer o seu pedido e jogar uma moeda no canal. ', 2975, 1, 4, '2009-08-26 23:48:18.505998', '2009-10-08 11:00:29.530287');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (9, 'Jardim Botânico de Brasília', 'SMDB conjunto 12, Lago Sul', '(61) 3366-4482', NULL, '', 'O Jardim Botânico é parada obrigatória para quem visita Brasília pela primeira vez. A fauna e a flora típicas do cerrado reservam algumas surpresas. Diferentemente de todos os outros parques do País, o jardim não é formado por plantas de várias regiões, e sim pela vegetação natural da região.

São cerca de 4,5 mil hectares, 526 destinados à visitação e quase 4 mil de reserva ecológica. Não se assuste se encontrar alguns animais em extinção, como o veado-campeiro, tatu-canastra e o tamanduá-bandeira. A dica é aproveitar a oportunidade e tentar fotografá-los.

Para quem gosta de ler ao ar livre, o parque conta ainda com uma biblioteca ecológica, inaugurada em março de 2007. O espaço é destinado às crianças.', 2975, 1, 4, '2009-08-26 23:44:50.983122', '2009-10-08 11:07:13.598638');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (11, 'Memorial dos Povos Indígenas', 'Eixo Monumental Oeste – Praça do Buriti', '(61) 3344-1155', NULL, 'Terça a sexta-feira, das 9h às 18h; sábados, domingos e feriados, das 10h às 18h', 'Em pleno Eixo Monumental uma construção na forma de espiral guarda a história de quem habitavam o território brasileiro antes da chegada dos portugueses. O Memorial dos Povos Indígenas foi inspirado nas malocas dos índios e em suas tradições. Por isso, ao projetar o museu, Oscar Niemeyer criou um pátio no meio do prédio e sugeriu que lá fossem realizados os eventos da casa, assim como os rituais no centro de uma aldeia.

Quando for visitar o memorial, não deixe de consultar a programação de atividades. Se der sorte de estar em Brasília no Dia do Índio, 19 de abril, você poderá conferir uma programação especial, com apresentações de tribos nacionais e, quem sabe, internacionais.

A riqueza e a diversidade da cultura indígena também podem ser conhecidas a partir do acervo do local, um dos mais valiosos do Brasil. Entre outras peças está nada menos que uma coleção etnográfica, com 382 peças, doada pelos antropólogos Darcy e Berta Ribeiro. A coletânea inclui exemplares da plumaria Urubu-Kaapor, reunidas durante quase 40 anos de pesquisa de campo.

Embora hoje o museu seja uma das principais referências nacionais sobre a cultura indígena, por anos sua existência foi posta em cheque. Em 1987, logo que a construção ficou pronta, o prédio não foi inaugurado para sua finalidade inicial e passou a ser um museu de arte moderna.

Somente depois de muitas manifestações e de fechar as portas diversas vezes, em 1999 o espaço se tornou, definitivamente, o Memorial dos Povos Indígenas. Essa conquista foi motivada por um fato que você deve lembrar: dois anos antes, alguns jovens haviam queimado o índio Gaudino Pataxó. O corpo dele foi velado no museu e serviu de alerta para a necessidade de criar uma cultura de respeito aos índios.', 2975, 1, 4, '2009-08-26 23:47:21.780769', '2009-10-08 11:01:06.109327');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (18, 'Legião da Boa Vontade-LBV', 'SGAS 915 Lotes 75/76', '(61) 3245-1070', NULL, 'Todos os dias, em qualquer horário', 'Esqueça dogmas ou extremismos religiosos. O Templo da Boa Vontade não foi feito para um grupo específico. Ao contrário: desde que foi inaugurado, em 1989, seu objetivo é ser o ponto de encontro da espiritualidade, cultura, arte, ecologia e medicina espiritual. O prédio foi construído pela Legião da Boa Vontade (LBV).
Com 21 metros de altura, essa pirâmide de sete faces é o local mais visitado pelos turistas em Brasília. E não é apenas pelo caráter de ecumenismo irrestrito, sem santos ou divindades nos altares. No ápice da obra, um cristal puro de 21 quilos ilumina o ambiente. Considerada por muitos a maior do mundo, esta jóia deixa qualquer um boquiaberto.
Quando for ao templo, não deixe de fazer o caminho da peregrinação. Basta tirar os sapatos e seguir a espiral de pedras negras desenhada no piso. Quando chegar ao centro, toque o círculo de cobre e levante as mãos para o alto. Dizem que este ritual atrai boas energias. Para se purificar, retorne pelas pedras brancas e, no final, tome um gole de água da fonte – que faz o mesmo percurso da espiral, mas por baixo da terra.

Além da meditação, você também pode visitar os espaços anexos à pirâmide, onde estão uma galeria de arte, o Memorial Alziro Zarur, a Sala Egípcia, o Salão Nobre, os jardins subterrâneos e o Parlamento Mundial da Fraternidade Ecumênica, construído em 1994 para abrigar conferências da LBV.', 2975, 1, 5, '2009-08-26 23:56:16.844433', '2009-10-08 10:58:51.833142');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (15, 'Pontão do Lago Sul', 'SHIS, QL10, LT. 1/33 - Pontão do Lago Sul', '(61) 3364-0580', 'pontao@pontaodolagosul.com.br', '', 'Conhecido pela bela paisagem, o Pontão do Lago Sul é um dos locais mais frequentados por quem procura bons restaurantes e um clima praiano.

Situado às margens do Lago Paranoá e próximo à ponte Lúcio Costa, o Pontão é parada obrigatória para aqueles que querem conhecer Brasília. Além da praça gastronômica, há também feiras de artesanato, shows musicais e parques para crianças.

Algumas pessoas aproveitam o lago artificial para praticar esportes náuticos ou passear de lancha. À noite, a iluminação dá um charme especial ao Pontão – lugar ideal para relaxar depois de um dia de trabalho.

Inaugurado em abril de 2002, o espaço com 134 mil m² e recebe cerca de 120 mil visitantes por mês. Apesar do grande movimento, não se preocupe com estacionamento: são 1,5 mil vagas.', 2975, 1, 4, '2009-08-26 23:52:39.78083', '2009-10-08 11:03:18.523765');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (17, 'Teatro Nacional', 'Setor Cultural Norte – Via N2', '(61) 3325-6105', NULL, 'Segunda a sexta-feira, das 15h às 17h30', 'Inaugurado em março de 1979, o Teatro Nacional Claudio Santoro é um projeto de Oscar Niemeyer e tem influência da arquitetura asteca. As obras, que começaram em 1960, foram realizadas em etapas. Enquanto o teatro não estava concluído, o local serviu de palco para concursos de beleza, bailes de carnaval, missas e eventos esportivos. Hoje, o teatro é o maior complexo da cidade destinado às artes. Além das salas de espetáculos Martins Pena, Alberto Nepomuceno e Villa-Lobos, o espaço conta ainda com uma galeria de artes plásticas. Ao visitar o local, fique atento aos jardins e às esculturas – “O Contorcionista”, de Alfredo Ceschiatti, e “O Pássaro” – que dão um toque especial ao ambiente. Em forma de pirâmide, o teatro também é espaço para boatos assombrados. Dizem que, durante a madrugada, funcionários já ouviram vozes e sons dos pianos das salas.', 2975, 1, 4, '2009-08-26 23:55:25.254333', '2009-10-08 11:05:57.580431');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (16, 'Santuário Dom Bosco', 'W3 Sul, Quadra 702', '(61) 3223-6542', 'contato@santuariodombosco.org.br', 'As cerimônias acontecem às 7h e às 18h, de segunda a sábado, e às 8h, às 11h, às 18h e às 19h30, no domingo', 'O Santuário Dom Bosco é mais uma homenagem ao padroeiro da cidade, o santo São João Melchior Bosco. Projeto de Carlos Alberto Naves, aluno de Oscar Niemeyer, a igreja tem 80 colunas estilo Brise Soleil que se fecham em arcos góticos.

Um dos destaques do santuário é o lustre central, formado por 7,4 mil peças de vidro murano, 180 lâmpadas e com peso aproximado de 3 toneladas. As portas descrevem a vida de Dom Bosco – que teve um sonho premonitório com a construção de Brasília. Para manter a igreja limpa, o pároco conta com a ajuda dos fiéis, que se organizam em mutirão a cada dois anos.

Quem quiser assistir a uma missa deve se programar para não perder os horários. A igreja tem capacidade para 1,2 mil pessoas. ', 2975, 1, 6, '2009-08-26 23:54:02.803854', '2009-10-08 11:10:13.393395');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (4, 'Complexo Cultural da República João Herculino', 'Setor Cultural Sul, Lote 2, próximo à Rodoviária do Plano Piloto - Zona 0', '(61) 3325-6410', NULL, 'Museu - Terça a domingo, das 9h às 18h30 / Biblioteca – Ligar para agendar', 'Depois de quase meio século, saíram do papel dois projetos de Oscar Niemeyer desenhados na época da construção de Brasília. No final de 2006, foram inaugurados o Museu Nacional Honestino Guimarães e a Biblioteca Nacional Leonel de Moura Brizola, que integram o Complexo Cultural da República João Herculino. 

Construídos numa área de 91,8 mil metros quadrados, os espaços são mais uma opção de lazer cultural gratuito. O museu foi criado para abrigar exposições de arte e oficinas de restauração de pinturas e esculturas. Fique atento à agenda de mostras e cursos. No formato de oca e cercado por uma passarela, o prédio em si já é uma obra de arte. 

A biblioteca, com acervo ainda em formação, tem estrutura para se tornar uma das mais modernas do País, principalmente no quesito inclusão digital. Comporta mais de 500 mil volumes impressos e 200 microcomputadores com acesso à internet e aos acervos de outras bibliotecas brasileiras.', 2975, 1, 6, '2009-08-26 23:36:54.989795', '2009-10-08 10:55:58.334052');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (1, 'Catedral Metropolitana', 'Esplanada dos Ministérios, Eixo Monumental – Leste', '(61) 3224-4073', NULL, 'Diariamente, das 8h às 18h', 'Patrimônio Histórico e Artístico Nacional, a Catedral Metropolitana de Brasília é considerada um marco na história da arquitetura e da engenharia brasileira. A obra de Oscar Niemeyer, inaugurada em 1967, pouco lembra as igrejas tradicionais – principalmente pela forma circular.

É fácil perceber a ousadia do projeto. Sua estrutura é composta por 16 enormes colunas, que saem do solo e se encontram no topo, formando uma espécie de coroa. O acesso ao interior é feito por uma passagem subterrânea revestida em preto, contrastando com o salão principal. Lá dentro, a luz natural que entra pelos vitrais do teto se reflete no mármore branco das paredes e colunas.

Outra surpresa é a acústica da igreja. Durante a visita, faça o teste: fique próximo à parede e peça para outra pessoa fazer o mesmo em qualquer outro ponto do salão. Quando você falar, ela ouvirá sua voz, como num telefone sem fio.

Além do ousado projeto arquitetônico, este templo também guarda importantes peças e obras de arte, como o altar-mor, doado pelo Papa Paulo VI, a Via-Sacra, de Di Cavalcanti, e os quatro evangelistas, de Alfredo Ceschiatti, cada um com três metros de altura.', 2975, 1, 5, '2009-08-26 23:31:13.703233', '2009-10-08 10:59:36.006065');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (5, 'Concha Acústica', 'Orla do Lago Paranoá - Setor de Hotéis e Turismo Norte', '(61) 3306-1065', NULL, 'Todos os dias, das 8h às 19h', 'Quem passa pelas margens do Lago Paranoá fica admirado com as formas da Concha Acústica. Projeto de Oscar Niemeyer inaugurado em 1969, o desenho parece se integrar perfeitamente à paisagem natural da região.

Mas é ao assistir a um espetáculo no local que se percebe o valor da obra. Numa área de mais de 8 mil m², o som da voz humana pode ser ouvido por até 10 mil pessoas, sem necessidade de amplificação. Isso porque o palco, localizado num nível inferior ao da platéia, tem concha acústica com 42 metros de comprimento e 5 metros de altura na parte mais elevada.

Torça para estar em Brasília em dia de espetáculo na Concha. Se isso não acontecer, você mesmo pode testar a acústica do local.', 2975, 1, 4, '2009-08-26 23:38:09.410923', '2009-10-08 11:05:21.574758');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (19, 'Torre de televisão', 'Eixo Monumental – Lado Oeste – Canteiro Central', '(61) 3322-6611', NULL, 'Todos os dias, das 9h às 18h', 'Para entender o Plano Piloto, pegue um mapa de Brasília e vá ao mirante da Torre de televisão. De uma plataforma de 75 metros de altura, é possível ver o eixo e as asas do avião que dá forma à cidade. No meio da planície, o destaque é a Esplanada dos Ministérios, com o Congresso Nacional ao fundo.

Projetada por Lúcio Costa para transmitir sinais de rádio e TV com alta qualidade, a torre é hoje um dos principais pontos turísticos da cidade. Não à toa: seus 224 metros de comprimento a tornam uma das mais altas estruturas do gênero na América Latina. Aos sábados e domingos, a tradicional feirinha de comidas e artesanatos lota o pátio ao redor da torre desde 1970.

Para subir ao mirante, não se preocupe com o cansaço, pois há um elevador à sua disposição. Antes de chegar ao ponto mais alto, você pode visitar o Museu Nacional de Gemas. Instalado na plataforma mais baixa da torre, a 25 metros do chão, o local guarda uma enorme variedade de pedras brasileiras, preciosas e semi-preciosas.', 2975, 1, 4, '2009-08-26 23:57:20.159541', '2009-10-08 11:06:43.729288');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (14, 'Parque da Cidade', 'Asa Sul de Brasília - entradas pelo eixo Monumental, setor de Indústria e Quadras 901, 906 e 910 Sul', '(61) 3225-2451', NULL, 'As atividades são gratuitas e acontecem de segunda a sexta, pela manhã', 'Se você acha que uma praia faz falta em Brasília, vai ter uma boa surpresa ao ar livre. O Parque da Cidade – Sarah Kubitschek é um complexo de diversão com área equivalente a 420 hectares, localizado na Asa Sul. O espaço, público e gratuito, atende a todos os gostos e idades: além de duas ciclovias, tem parque infantil, lago com pedalinhos e caiaques,z churrasqueiras, campos de futebol, kartódromo, campo de aeromodelismo, anfiteatro e estádio hípico.
O Parque é ideal para a prática de atividades físicas e para a diversão em família. Uma boa dica é o passeio nos pedalinhos do lago, onde pais e crianças podem andar juntos. Se o dia estiver bonito, dá até para fazer um piquenique nos quiosques ou no gramado.
Quem tem mais de 60 anos pode participar de aulas de Tai Chi Chuan, ioga e condicionamento físico.
Para ser criado, o Parque da Cidade contou com a experiência de três grandes nomes da área: Oscar Niemeyer (arquitetura), Burle Marx (jardins) e Lúcio Costa (urbanismo). Só por isso já dá para imaginar que a visita vale mesmo a pena.', 2975, 1, 10, '2009-08-26 23:50:51.302532', '2009-10-08 11:08:14.624794');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (6, 'Congresso Nacional', 'Praça dos Três Poderes', '(61) 3216-1771', NULL, 'Todos os dias do ano, inclusive feriados, das 9h às 17h (visitas guiadas de 30 em 30 minutos, a partir de 9h30).', 'Cartão postal de Brasília, o Congresso Nacional é mais do que a sede do Poder Legislativo. Símbolo da arquitetura de Oscar Niemeyer, a obra se destaca na paisagem plana e organizada da cidade. Além da beleza, o desenho do projeto desafiou os engenheiros da época.

No final dos anos de 1950, a sustentação de duas enormes cúpulas exigiu semanas de cálculos complexos. O trabalho de muitos profissionais deu forma côncava ao plenário do Senado Federal e convexa ao plenário da Câmara dos Deputados.

Nas duas torres do edifício central ficam as áreas administrativas e técnicas do Congresso. A altura dos prédios ilustra a importância e a representatividade do local: com 28 andares ou 100 metros de comprimento, eles foram projetados para serem sempre os mais altos da capital federal.

Diariamente, são realizadas visitas monitoradas ao Congresso Nacional. Não deixe de passar pelos Salões Negro, Verde e Nobre, os plenários e as galerias. Se der sorte, você pode assistir a uma sessão da Câmara ou do Senado e até encontrar o seu candidato das últimas eleições. Do lado de fora, os jardins projetados por Burle Marx são uma atração a parte. Valem a pena conhecer.', 2975, 1, 4, '2009-08-26 23:40:12.225722', '2009-10-08 11:08:59.484509');
INSERT INTO tourist_sights (id, name, address, phone, email, visitation_period, description, city_id, user_id, hits, created_at, updated_at) VALUES (20, 'Parque Nacional de Brasilia Água Mineral', 'Rodovia BR - 040 - SMU - Via EPIA', '(61) 3465-2013', NULL, 'Diariamente, das 8h às 16h', 'A apenas 10 km do centro do Plano Piloto há uma paisagem inimaginável em qualquer grande cidade: um espaço com nada menos que 30 mil hectares de árvores, trilhas e duas piscinas naturais de águas cristalinas. É o Parque Nacional de Brasília, mais conhecido como Água Mineral. Quando o assunto é qualidade de vida, este é um dos destinos preferidos dos moradores da capital.

Não faltam opções de lazer. Uma boa dica é começar o dia com um banho relaxante nas piscinas de água mineral. Depois, quem gosta de caminhada pode escolher uma das duas trilhas: a da Capivara, com duração de 20 minutos (1,3 km) ou a do Cristal Água, que pode ser feita em 1 hora (5 km). Ao final do passeio, o melhor é apreciar a vista da Chapada da Contagem, a Depressão do Paranoá e a Encosta da Contagem. Também dá para recarregar as energias num piquenique ao ar livre

O parque tem uma fauna com mais de 300 espécies de pássaros – como ema, seriema e tucano – e alguns animais em extinção, entre eles o lobo-guará, o tamanduá bandeira e o tatu canastra. Se você quer conhecer melhor as espécies nativas da flora e da fauna do cerrado, visite o museu que fica no Centro de Visitantes do local.', 2975, 1, 4, '2009-08-26 23:58:12.709254', '2009-10-08 11:09:30.959633');

SELECT setval('tourist_sights_id_seq', 20);
